dataset_path: "data/dataset.h5"
batch_size: 128        
channels: 64          
num_res_blocks: 4
dropout: 0.15           
weight_decay: 0.0005 
lr_scheduler: "cosine"
lr: 0.0001              
epochs: 30
finetune_epochs: 20
finetune_lr: 0.00001
finetune_batch_size: 128
use_value_head: false
ELO: 1300
username: "JarJarAmidala"
pgn_path: "data/games.pgn"
onnx_output_path: "static/models/model.onnx"
quantized_output_path: "static/models/model_quantized.onnx"
checkpoint_path: "checkpoints/best_model.pt"
